Kernel = None
Hardware = None
Settings = None
fucky_wucky = False



#DEFAULT_COLOR = 0xB5B6
DEFAULT_COLOR = 0x5155
DEFAULT_BG_COLOR = 0
DEFAULT_OUTLINE_COLOR = 0x7BCF
DEFAULT_TEXT_COLOR = 0xFFFF
DEFAULT_YESCOLOR = DEFAULT_OUTLINE_COLOR
DEFAULT_NOCOLOR = DEFAULT_BG_COLOR
DEFAULT_TEXT_RATIO = 30  #characters per line, 30 for 240x240 screen with 8 pixel large font
DEFAULT_TEXT_RATIO_INV = 1.0/DEFAULT_TEXT_RATIO  #expensive maths
DEFAULT_TEXT_RATIO_INV_2 = DEFAULT_TEXT_RATIO_INV/2.0
